### ISSUE TITLE
/sys/kernel/mm/lru_gen/enabled resets to 0x0003 after unlocking

### ISSUE THREAD

**Issue by Nixola** [LukeSkyD/NP1-MGLRU-FIX#1]
Hi, I'm just letting you know that V2 still behaves the same way on my phone; after putting my pin in, it resets to 0x0003. This is after installing the module, fully shutting the phone down, and turning it back on. I'm not really asking for a solution as I'm fine using `resetprop` for the time being, just letting you know here without going off-topic again on the Magisk issue.

**Comment by LukeSkyD** [comment]
> Hi, I'm just letting you know that V2 still behaves the same way on my phone; after putting my pin in, it resets to 0x0003. This is after installing the module, fully shutting the phone down, and turning it back on. I'm not really asking for a solution as I'm fine using `resetprop` for the time being, just letting you know here without going off-topic again on the Magisk issue.

Thanks for the heads up, I would like to implement a script which runs every time system.prop is written and resets mglru_enable, but im short on time rn.
I'll do it as soon as i can!

In the meantime, can you share your magisk log? from boot to after unlock, maybe there is something i can use.

**Comment by Nixola** [comment]
Sure. Here's the log right after a cold boot and unlocking the phone, with your module (v2) installed: 
[magisk_log_2023-04-05T12.26.26.log](https://github.com/LukeSkyD/NP1-MGLRU-FIX/files/11157791/magisk_log_2023-04-05T12.26.26.log)
Thanks for looking into this!

**Comment by LukeSkyD** [comment]
> Sure. Here's the log right after a cold boot and unlocking the phone, with your module (v2) installed: [magisk_log_2023-04-05T12.26.26.log](https://github.com/LukeSkyD/NP1-MGLRU-FIX/files/11157791/magisk_log_2023-04-05T12.26.26.log) Thanks for looking into this!

persist.sys.mglru_enable is stored in /data/property/persistent_properties which i would prefer to leave writable so i have to find which process is resetting prop.
In magisk's logs there is nothing about it, happened to me this night, was not able to track down the culprit.
I'm researching for the use of sepolicy rules and deny processes to ever writing to that single property

**Comment by LukeSkyD** [comment]
> Sure. Here's the log right after a cold boot and unlocking the phone, with your module (v2) installed: [magisk_log_2023-04-05T12.26.26.log](https://github.com/LukeSkyD/NP1-MGLRU-FIX/files/11157791/magisk_log_2023-04-05T12.26.26.log) Thanks for looking into this!

[mglruDisablerV3b.zip](https://github.com/LukeSkyD/NP1-MGLRU-FIX/files/11170230/mglruDisablerV3b.zip)

Can you try this version?

**Comment by Nixola** [comment]
I'm assuming I should install it and perform a cold boot as usual?

**Comment by LukeSkyD** [comment]
> I'm assuming I should install it and perform a cold boot as usual?

Yes

**Comment by Nixola** [comment]
Seems to work so far, as in unlocking the phone doesn't set mglru back on. I'll let you know if I notice any instability, crashes, or random reboots (which, while rare, did happen). Thanks again!

**Comment by LukeSkyD** [comment]
> Seems to work so far, as in unlocking the phone doesn't set mglru back on. I'll let you know if I notice any instability, crashes, or random reboots (which, while rare, did happen). Thanks again!

Perfect thank you for your feedback yes please let me know.

**Comment by Nixola** [comment]
I was playing Wild Rift, the phone just locked up (not enough to prevent adb from working), and mglru was enabled again.

**Comment by LukeSkyD** [comment]
> I was playing Wild Rift, the phone just locked up (not enough to prevent adb from working), and mglru was enabled again.

Can you try this other version?
[mglruDisablerV3b2.zip](https://github.com/LukeSkyD/NP1-MGLRU-FIX/files/11171736/mglruDisablerV3b2.zip)

**Comment by Nixola** [comment]
V3B2 doesn't seem to work at all; before testing it, I did try and re-test V3B and that one didn't work either this time, even though it did earlier, so maybe it's inconsistent?

**Comment by LukeSkyD** [comment]
> V3B2 doesn't seem to work at all; before testing it, I did try and re-test V3B and that one didn't work either this time, even though it did earlier, so maybe it's inconsistent?

[mglruDisablerV3b3.zip](https://github.com/LukeSkyD/NP1-MGLRU-FIX/files/11185519/mglruDisablerV3b3.zip)

What about this? Remember to cold boot

**Comment by Nixola** [comment]
Nope, cold-booted, it still reset to true a few seconds after unlocking the phone.

**Comment by LukeSkyD** [comment]
> Nope, cold-booted, it still reset to true a few seconds after unlocking the phone.

What's the result of
```ls -l  /sys/kernel/mm/lru_gen/enabled```

**Comment by Nixola** [comment]
After disabling mglru via resetprop:

`---------- 1 root root 4096 2023-04-09 16:04 /sys/kernel/mm/lru_gen/enabled`

**Comment by LukeSkyD** [comment]
> After disabling mglru via resetprop:
> 
> `---------- 1 root root 4096 2023-04-09 16:04 /sys/kernel/mm/lru_gen/enabled`

Ok, it could be possible that the prop resets to true but mglru stays disabled.
Cold boot the phone, when persist.sys.mglru_enable gets reset to true, what's the result of
``` cat /sys/kernel/mm/lru_gen/enabled```

**Comment by Nixola** [comment]
I had to `chmod o+r` it or it wouldn't let me; it's `0x0000`

**Comment by LukeSkyD** [comment]
> I had to `chmod o+r` it or it wouldn't let me; it's `0x0000`

Ok perfect, can you check if with mglru_enable true and that file to 0 the phone still crashes? Seems like the property could be true with mglru disabled.

**Comment by Nixola** [comment]
The property is indeed true, I haven't used the phone much since checking but it hasn't crashed yet which, given the time it usually takes to crash without your module or any intervention, probably means it's disabled despite the flag being true. This'll make me much less nervous about my phone randomly crashing while I'm not home. Thanks again, and sorry for the trouble!

**Comment by LukeSkyD** [comment]
> The property is indeed true, I haven't used the phone much since checking but it hasn't crashed yet which, given the time it usually takes to crash without your module or any intervention, probably means it's disabled despite the flag being true. This'll make me much less nervous about my phone randomly crashing while I'm not home. Thanks again, and sorry for the trouble!

Absolutely don't worry it's very interesting to dig into this problem, it's a pity that i cannot find much infos about how everything's working.

I hope this one will be the final one, spare rare crashes are still possible, the most important thing is that they are not common. Let me know thanks for all your feedback!

**Comment by LukeSkyD** [comment]
> The property is indeed true, I haven't used the phone much since checking but it hasn't crashed yet which, given the time it usually takes to crash without your module or any intervention, probably means it's disabled despite the flag being true. This'll make me much less nervous about my phone randomly crashing while I'm not home. Thanks again, and sorry for the trouble!

Have you experienced any crash?

I've been using b3, persist.sys.mglru_enable is true but no crashes for me.

**Comment by Nixola** [comment]
Haven't experienced any further crashes so far, I think this is
the most stable this phone has ever been since I installed 1.5.3.

**Comment by LukeSkyD** [comment]
> Haven't experienced any further crashes so far, I think this is the most stable this phone has ever been since I installed 1.5.3.

Perfect, I'm pushing the update.
It will still be different from b3, so an update is recommended.
Cold boot will no longer be necessary too.
I'll be closing this issue tomorrow if nothing get reported.

**Comment by LukeSkyD** [comment]
Issue closed as nobody reported mglru reboots after V3 release.
